version: "3"

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "dev_user"
      POSTGRES_PASSWORD: "dev_password"
      POSTGRES_DB: "dev_db"
    networks:
      - backend
    ports:
      - "5432:5432"

  fastapi:
    build: ./fastapi
    volumes:
      - ./fastapi:/backend
    environment:
      - DATABASE_URL=postgresql://dev_user:dev_password@db:5432/dev_db
    networks:
      - backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always

networks:
  backend:
    internal: true

volumes:
  postgres_data_dev: